# Generated by Django 5.2.5 on 2025-08-30 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Claims",
            fields=[
                ("claim_id", models.IntegerField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=255)),
                ("billed_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=50)),
                ("insurer_name", models.CharField(max_length=255)),
                ("discharge_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ClaimDetail",
            fields=[
                ("detail_id", models.IntegerField(primary_key=True, serialize=False)),
                ("cpt_codes", models.TextField()),
                ("denial_reason", models.TextField()),
                (
                    "claim_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="claims.claims",
                    ),
                ),
            ],
        ),
    ]
